version: '3.9'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    volumes:
      - ./zookeeper:/data

  kafka:
    image: bitnami/kafka:2.8.1
    container_name: kafka
    ports:
      - 9092:9092
    volumes:
      - ./kafka_data:/bitnami/kafka/data
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  redis:
    image: redis
    container_name: redis
    ports: 
      - 6379:6379
    volumes: 
      - ./data/redis:/data
      - ./config/redis.conf:/redis.conf
    command: redis-server /redis.conf
